# Generated by Django 5.1.3 on 2024-12-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contributions',
            field=models.JSONField(default=dict),
        ),
    ]
