# Generated by Django 5.1.3 on 2024-12-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_contributions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contributions',
        ),
    ]
