# Generated by Django 5.1.3 on 2024-12-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_post_canva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canva',
            name='content',
        ),
        migrations.AddField(
            model_name='canva',
            name='sizeHeight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
