# Generated by Django 5.1.3 on 2024-12-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_canva_content_canva_sizeheight'),
    ]

    operations = [
        migrations.AddField(
            model_name='canva',
            name='sizeWidth',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
