# Generated by Django 5.1.3 on 2024-12-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_canva_sizewidth'),
    ]

    operations = [
        migrations.AddField(
            model_name='canva',
            name='timer',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
