# Generated by Django 5.1.3 on 2024-12-03 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_canva_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
                ('canva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pixels', to='blog.canva')),
            ],
        ),
    ]
