# Generated by Django 5.1.3 on 2024-12-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_pixel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pixel',
            unique_together={('canva', 'x', 'y')},
        ),
    ]
