# Generated by Django 5.1.3 on 2024-12-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_canva_joined_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedcanva',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
