# Generated by Django 5.1.3 on 2024-12-03 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_canva_joined_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canva',
            name='joined_users',
        ),
        migrations.DeleteModel(
            name='JoinedCanva',
        ),
    ]
