# Generated by Django 5.1.3 on 2024-12-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_canva_joined_users_delete_joinedcanva'),
    ]

    operations = [
        migrations.AddField(
            model_name='canva',
            name='save_count',
            field=models.IntegerField(default=0),
        ),
    ]
