# Generated by Django 5.1.3 on 2024-12-05 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_userpixelactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='canva',
            name='save_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('canva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.canva')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'canva')},
            },
        ),
        migrations.DeleteModel(
            name='UserPixelActivity',
        ),
    ]
