# Generated by Django 5.1.3 on 2024-12-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_useraction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraction',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='canva',
            name='save_count',
        ),
        migrations.AddField(
            model_name='useraction',
            name='modification_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
