# Generated by Django 5.1.4 on 2024-12-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_canva_save_count_useraction_delete_userpixelactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='modification_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
