# Generated by Django 5.1.3 on 2024-12-05 10:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_useraction_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixelModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pixel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='blog.pixel')),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
    ]
