# Generated by Django 5.1.4 on 2024-12-05 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_useraction_modification_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraction',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='canva',
            name='save_count',
        ),
    ]
